### ISSUE TITLE
add pep8 speaks to repository

### ISSUE THREAD

**Issue by alperyeg** [IGITUGraz/L2L#115]
Instead of using the style-checker `run-style-check.sh` I would like to recommend to use [pep8 speaks](https://pep8speaks.com/) instead. One can configure it in the same fashion as the checker script and it can run e.g. only on the code of the actual pull request. Right now the CI always breaks because of all pep8 issues from all files. Is this a volitional behavior?

**Comment by anandtrex** [comment]
I have added pep8speaks to the repository. It should be activated on new pull requests.
