### ISSUE TITLE
Index confusion

### ISSUE THREAD

**Issue by chanokin** [IGITUGraz/L2L#118]
Hi! In this portion of the optimizer, what I understand is that you first check if there are repeated individuals, and then you want to mutate those repeated

https://github.com/IGITUGraz/L2L/blob/5e1695a40e269d144ab78ae6213dea3abc938bb0/l2l/optimizers/evolution/optimizer.py#L173-L180

But  in line 176, I think the iteration should start with `i+1` instead of `i`. Otherwise , since your second loop starts with the same individial as the first one, you would be mutating all individuals 80% probability. Furthermore, I believe that, in line 175, offspring should iterate on `[:-1]`.

**Comment by chanokin** [comment]
Also, after line `179` we should delete the fitness value so these mutants get evaluated again:

```python
del o2.fitness.values
```

**Comment by anandtrex** [comment]
HI @chanokin Agreed. Thanks for debugging this code. Could you please send a pull request?
